name: Reduce disk space
description: Reduce disk space usage
runs:
  using: composite
  steps:
    # https://github.com/actions/runner-images/issues/2840#issuecomment-3641541098
    - name: Disk space cleanup
      shell: sh
      run: |
        sudo df -TBG /
        sudo rm -rf /opt/microsoft
        sudo rm -rf /usr/lib/llvm-*
        sudo rm -rf /usr/local/julia*
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/share/swift
        sudo df -TBG /
