FROM debian:13.2 AS base

LABEL maintainers="contact@wikiteq.com,pavel@wikiteq.com,alexey@wikiteq.com"
LABEL org.opencontainers.image.source=https://github.com/WikiTeq/Taqasta

{{ template "templates/base.Dockerfile" -}}

FROM base AS core

{{ template "templates/core.Dockerfile" -}}

FROM base AS skins

{{ template "templates/skins.Dockerfile" -}}

# Multiple stages to capitalize on layers caching
{{ template "templates/extensions.Dockerfile" -}}

FROM base AS composer

{{ template "templates/composer.Dockerfile" -}}

FROM base AS final

{{ template "templates/final.Dockerfile" -}}

EXPOSE 80
WORKDIR $MW_HOME

HEALTHCHECK --interval=1m --timeout=10s \
	CMD wget -q --method=HEAD localhost/w/api.php

CMD ["/run-apache.sh"]
