---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: wiki-secrets
spec:
  encryptedData:
    MW_ADMIN_PASS: AgBjckMJh44pvx9nRzewLoQJTy6WccNbbbTd9i/b99CpyFlNe+9UFiKZGg+BrHS0bExAtvcbSAdGN5E7B9+fBLfM5fXBl3PnSqbh+nGk2kfsBfBDoOERypGjJHoL9QOq7/nCsbjIopC0EXhfcZGSzlrGrMefsuRworXf23n+nn9dsf3L6AmiHrYl6lk0jl2Vz5E1Lcr7l2IXU84EnRnvvDSJPztSMoxght4Rx8M6T6bPUjh5ySSDGvh16XheN+gBpU9tkDxMD/9dHrRb1KnBdSY/3KFvHlB0v6iN1saw7ad4d5CXjySLvVTu3RW0wvnZMsqlC1LiuV7OQ0HoXFIbdyXDqSiECV+K4SvLYyHU3HSaFpR2L+aepIt0cM0y87cWHSQTf3aZk2JT3JS+m3VAdXZJ0vHUi5MYYZpEjr4ADfH0YeMpg7H9OAzoqBs8/veGRxu3nOmRR7bbIQCOTbXq/JCs5m0XpWeblkshNqsWoYL2IQdtDrKVa1MeEKAwjNDAHiK5BX2HZaRTKZ3Oe/62cD78atdEJsPhZNReA5zeBoBTH3oZXYlaL+Eh63I6bZBYz5tA/43V+NRJ4lJM/y2PJ6EQP3szfveeQngUtY2zxW9tGbAV4q+CIMGIGutaaVlULyljSz0GNlEV1q7wV+P2XRhYUtmUT0KzSNtQUX+ZGhonP1amrbW6E67jKEzGzf71NL3fvZJ+mRg/rQlx
    MW_ADMIN_USER: AgA+Owj1zOWeGrNMxALttMfFNtW1uNQg/hhr6vOxJmDvgVl4hFdeldY4pb4bmftVBOcX51mXGFh+e3Xh7KBgfsvX+ZdAbNfrrsJMuxXlE54udHHSKpLRZ+mISIhc8FRHQ+0OTQv2x2rOBv6I4GRl3Vp5P3ad79HBy9WAQ9/Z651prrvErK6TacHlJiLKRDKvRH6TAYGT6zZr4xrjOg69JNvrbEDkFHuzKNMmkTnywo+bn962taRV3oAUHZPNLxuixBkcaNIH4VpmKkmWPqfeXUHD+WrC2bagb8OYOxTuvLLhnADznF6THOSrCXfYbpdvO6RFz8ym58dXFMqFqOHzggaA6kC+TAJmdKXbahq9MwxGEPaBqNVw4RF30SkM3nzohAk2MX5t6s3o1ZvU26pUbw9dQrbsvfrAJadWmJ2DVZBuQ3g6PSMv4Vr0rK16RoXGF9VT1gVTkRedN9ksn48Rh8hP0v1k2lCi9AKQvwXXCXIk1g+FbQTu/Gtd9RVxCMH3le/0RopCuCMkQA9y+2wc32a+1T4uQPN2ZN0jHFsd7lOC+Gil8iJozWUTEKE7coqe4TTAGfGBVcvyGu1jUmmNI4vVNOzsXy7dzfOjiNFJSQWwD5BbZD1U5fGm90yPRump5QnbrXr/x9CjdmpJI++e0SI4MZ+XE+TIxUhxM3wG5UCGGev+JFvtmJrDVK8XEz0CLDaIGjOKTg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: wiki-secrets
    type: Opaque
