---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: tailscale-auth
spec:
  encryptedData:
    authkey: AgCJPscbNNYqLy14H5V+7ZKulnQ+A3UHISJjljCmwXwJBX43SqBJkmgJ6z3EIz8abSkBz3GNbNU5AbXn/zO1utlbBfTtnzj7ZE5qnk9T/NB5ARWCJGs63t8BRMPtAQGO/e/zND/cOPKDO2haQOObvhLYo1dmEOjuw0cPekKUbOQcZhGVEZ128ox9Ydtpwss4g2K0biAz5bqTR1tfPG0kJD7QzjOTrYxgX7UccyRnJWycYThyVXTKeBKcdlcHKCZ7bmtr1BoWAAZo/vcf3DaKkQ4wihr4Vc0qmzBTbYoP5OiOwLvVb20oFSZOEu2eQuZcq0qAWE94vQnkjuWcH9uG1b9D0IBXPlvYbtmDFc5oLwrwdKk5BrpeBBxc8J+WvnAE1DuUaMQZT2xyjYdWkAgNBfSVYBS8vR1+M3Fwh+uqMF2qPAJjEixyGNNsj5mSH46/M9OCJllyGnhOpUmQXpnZAOBkq9RpwjbvyPrBWotVGcfrufovZuBb4OL94KcZInh62eRF0Sgd0UgRrrsKvDKKiVotqQhUGLKWwfhFDhZwZtYHS+JuCbddr3Cb00G/64oVVl70vfZFPVf22w5Y/1LGbluAdbkiw6dzKLwMX16eDhEQHdK5VePOQjL48q/4YZHOJg7LaY6rOP3KBklhHp3P6oZa/CZj63LZDuW+WOqdjk4Bm/nUI/y4xZf3RcIrm3ZuRU4/j66a+So/4zyX03cxFICbHBYNqqxFEQPrlZC2/ujjMRexBKecBibVYGSNyUFiqBxpf2pQGDqvCN6Ru4wl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: tailscale-auth
    type: Opaque
