---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: varnish-secret
spec:
  encryptedData:
    secret: AgBBVf9j0Hc5xMXGlYWNKTgWiUVdQ9Yq8A3zW/3U191UtDXB4tvercgKAMwNC7LHlUcOux24KYzGX5S+sJP3/rhnvF7Ta2wR2Kb7xKgp7jzRWlP72aym6LVywBb8vmzGs2RtdYazbbPI7rG+6Bc5KQsydE4JntngrhTB/E8e+1zkXMnQPHBTJM3247VQABNDRXanYGFUqCinHyKnU71ySbBG/V/9WM2bqOzwgsQGGzH0Ftmbp8b4QvavFudLsM9SL3sqzPEQcifwfYkPy4IEAz9IeSJZMyxwly80/11kJ+AA62jIo+V81UXESMUWZ9pFZJgYuKDPHzd33fuHbt7g1JsZQiflFIUfDYWz5TujrJZ8mzQAO0qLyX7n6kiHoZrzJdk5cIPs9V78huJSQeSlGx8kmhpabOBkMJb61yFhSo0Yg1MXV4+FQ+jZQKeFX3jdSB08xexFzDiiY8x0noG23XwYjT3rNoZKKge6ncaPjZd2szcMw5CIIC0aWWgLTOhXu9Cj8UdFRbfN/kp13WUwQVR9xMp9nHW7HjQETimldRG5v30SglqtYkymaJwbMbU8dYbjz/y/zrVXoEhvd7ZTbfMDDsEAN355A1QyoyheJU+UD/1cLUIAj4dMzoOtsltMbqmJLRb4Xl7G6eAr13RODnb/evLFkTK+IsLUcq1a1TyETNTmVQZ8guaHHGjAjLXGGCFuejsVFyr8sO/lcGuTtxSctVB/Mv6Z6vue8bJQut5kofQ5EGcbz3yGF/LBOA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: varnish-secret
    type: Opaque
